name: Build Container

# Workflow disabled - uncomment to re-enable
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   workflow_dispatch:

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image-tag: 'test'
      run-tests: true
