name: MSDO Security Scan

# Workflow disabled - uncomment to re-enable
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   workflow_dispatch:

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  msdo-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ vars.REGISTRY_HOST }}/${{ vars.ARTIFACT_NAME }}:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Microsoft Security DevOps Action
      uses: microsoft/security-devops-action@latest
      with:
        tools: 'trivy'
      env:
        GDN_TRIVY_ACTION: image
        GDN_TRIVY_TARGET: ${{ vars.REGISTRY_HOST }}/${{ vars.ARTIFACT_NAME }}:latest
