name: MSDO Security Scan

on:
  push:
    branches-ignore: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image-tag: 'test'
      run-tests: false
      
  msdo-scan:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Run Microsoft Security DevOps Action
      uses: microsoft/security-devops-action@latest
      with:
        tools: 'trivy'
      env:
        GDN_TRIVY_ACTION: image
        GDN_TRIVY_TARGET: ${{ needs.build.outputs.image-name }}
