name: Quick Trivy Scan

# Workflow disabled - uncomment to re-enable
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   workflow_dispatch:

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ vars.REGISTRY_HOST }}/${{ vars.ARTIFACT_NAME }}:test
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Quick Trivy scan (High/Critical only)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ vars.REGISTRY_HOST }}/${{ vars.ARTIFACT_NAME }}:test'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'  # Don't fail the build, just report
