name: Quick Trivy Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image-tag: 'test'
      run-tests: false
      
  trivy-scan:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Quick Trivy scan (High/Critical only)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ needs.build.outputs.image-name }}'
        format: 'table'
        severity: 'CRITICAL,HIGH'
        exit-code: '0'  # Don't fail the build, just report
