name: Build and Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly security scans on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: vulnerable-app:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'vulnerable-app:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Run Trivy scanner (JSON format)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'vulnerable-app:latest'
        format: 'json'
        output: 'trivy-results.json'
        
    - name: Run Trivy scanner (Table format for logs)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'vulnerable-app:latest'
        format: 'table'
        
    - name: Upload Trivy scan results as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-scan-results
        path: |
          trivy-results.sarif
          trivy-results.json
        retention-days: 30
        
    # Optional: Fail the build if critical vulnerabilities are found
    - name: Run Trivy scanner with exit code
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'vulnerable-app:latest'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
      continue-on-error: true  # Set to false if you want to fail the build on vulnerabilities
      
  # Separate job for container security best practices scanning
  container-security:
    runs-on: ubuntu-latest
    needs: build-and-scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image for security scan
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: vulnerable-app:security-scan
        load: true
        
    - name: Run Trivy config scan (Dockerfile)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'table'
        
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        
    - name: Run Trivy secret scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'secret'
        scan-ref: '.'
        format: 'table'
